### ISSUE TITLE
doesn‘t start training after running the code

### ISSUE THREAD

**Issue by MyChocer** [leokarlin/LaSO#10]
Hi,
when I run the training script, it does not start training and the terminal freezes as the content below. Did I omit some important step?
''
python train_setops_stripped.py --resume_path=<path_to_LaSO_models>/paperBaseModel --init_inception=True --sets_basic_block_name=SetopResBasicBlock --sets_block_name=SetopResBlock_v1 --sets_network_name=SetOpsResModule --ops_latent_dim=8092 --ops_layer_num=2 --base_network_name=Inception3 --crop_size=299 --epochs=50 --train_base=False --coco_path=<path to local coco folder> --results_path=<base path for results>
''

**Terminal output**
`[Main] WARNING | Unrecognized alias: '--results_path=../results_vg', it will probably have no effect.
INFO:root:Created results path: /tmp/results/train_setops_stripped/0068_4825993/noJobID/200221_011551
Writing default config to: /tmp/results/train_setops_stripped/0068_4825993/noJobID/200221_011551/config.py
GET /api/2.0/mlflow/experiments/list?view_type=ALL HTTP/1.1
Host: localhost:5000
User-Agent: mlflow-python-client/1.2.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
`

**Comment by mohong96** [comment]
Have u solved the question?
I have the same question now,i will be grateful if u can share the solution,thx.

**Comment by MyChocer** [comment]
> Have u solved the question?
> I have the same question now,i will be grateful if u can share the solution,thx.

I run the command
'''
mlflow server --host localhost
'''
before running the training script. 

In fact, the [page](https://github.com/leokarlin/LaSO) shows that it is the prerequisite to run the training code. But I ignored this before.

**Comment by mohong96** [comment]
> > Have u solved the question?
> > I have the same question now,i will be grateful if u can share the solution,thx.
> 
> I run the command
> '''
> mlflow server --host localhost
> '''
> before running the training script.
> 
> In fact, the [page](https://github.com/leokarlin/LaSO) shows that it is the prerequisite to run the training code. But I ignored this before.

thx,i ignored it too.
