### ISSUE TITLE
Does anyone run "test_ augmentation.py ”successfully?

### ISSUE THREAD

**Issue by mohong96** [leokarlin/LaSO#12]
1.when i use the command line：“python test_augmentation.py --base_network_name='Inception3' --batch_size=4 --class_cap=5 --class_ind_dict_path='<LaSO folder>/data_for_augmentation/5shotRun1ClassIdxDict.pkl' --classifier_name='Inception3Classifier' --crop_size=299 --g_inner_dim=2048 --init_inception=1 --latent_dim=2048 --lr=0.01 --n_epochs=50 --paper_reproduce=1 --resume_path=<path_to_LaSO_models> --sets_basic_block_name='SetopResBasicBlock' --sets_block_name='SetopResBlock_v1' --sets_network_name='SetOpsResModule' --used_ind_path='<LaSO folder>/data_for_augmentation/5shotRun1UsedIndices.pkl' --results_path=<folder path to save models> --coco_path=<path to local coco folder>”
The error is：test_augmentation.py: error: unrecognized arguments: --base_network_name=Inception3 --classifier_name=Inception3Classifier --g_inner_dim=2048 --init_inception=1 --paper_reproduce=1 --sets_basic_block_name=SetopResBasicBlock --sets_block_name=SetopResBlock_v1 --sets_network_name=SetOpsResModule
![image](https://user-images.githubusercontent.com/49022521/88188964-18ed6700-cc6b-11ea-8b7a-7cbd1511c993.png)

**Comment by mohong96** [comment]
2. i do not know how to find "/dccstor/alfassy/saved_models/FVClassAug5AVG2018.10.30.15:32usedIndicesRun4.pkl' 、‘'/dccstor/alfassy/saved_models/FVClassAug5AVG2018.10.30.15:32ClassIdxDict16Run4.pkl' and “/dccstor/alfassy/finalLaSO/code_release/trainedModels” 
![image](https://user-images.githubusercontent.com/49022521/88189208-64a01080-cc6b-11ea-9af3-2a8fb8ced53b.png)
![image](https://user-images.githubusercontent.com/49022521/88189272-7681b380-cc6b-11ea-8d3f-6a0a5a18494d.png)

**Comment by mohong96** [comment]
I'm very interested in laso, but I don't know how to solve the above two problems. If anyone has a solution, please let me know. Thank you

**Comment by zscd** [comment]
I am confused about this too

**Comment by alfassy** [comment]
Hi,

I fixed the README of this repository to have a working run command for augmentation, thank you for pointing our the bug.
for "used_ind_path" and "class_ind_dict_path" you need to use the files from the "data_for_augmentation" folder, look at the example run command.
you are supposed to use your own local paths, for me it was /dccstor/alfassy/... . 
The models can be downloaded through the google drive link in the READEME
