### ISSUE TITLE
About the correspondence between experimental results and tables of the paper

### ISSUE THREAD

**Issue by hyqyoung** [leokarlin/LaSO#18]
Sorry that I am new to the few-shot learning, I can now run the three files 1. train_setops_stripped.py, 2. test_precision.py and 3. test_augmentation.py under ./scripts_coco, but may I ask how the results of these scripts correspond to the tables in the paper? Thanks!

**Comment by alfassy** [comment]
The results of those scripts should be very close to the tables in the paper, see the README file for updated numbers expected from these tables. 
Sorry for the super late answer :)
