### ISSUE TITLE
ImportError: cannot import name 'EpochMetric'

### ISSUE THREAD

**Issue by pratikm141** [leokarlin/LaSO#4]
When I run 
python train_setops_stripped.py --inception_transform_input=False --resume_path=LaSO_models/resnet_base_model_only --resume_epoch=49 --init_inception=False --sets_basic_block_name=SetopResBasicBlock --sets_block_name=SetopResBlock_v1 --sets_network_name=SetOpsResModule --ops_latent_dim=8092 --ops_layer_num=2 --base_network_name=resnet50 --crop_size=224 --epochs=50 --train_base=False --coco_path='~/data_local/coco' --results_path='./results/'

I get the following error
Traceback (most recent call last):
  File "train_setops_stripped.py", line 20, in <module>
    from oneshot.ignite.metrics import EWMeanSquaredError
  File "/home/pratikm/work19/LaSO/oneshot/ignite/metrics/__init__.py", line 1, in <module>
    from .metrics import EWMeanSquaredError
  File "/home/pratikm/work19/LaSO/oneshot/ignite/metrics/metrics.py", line 6, in <module>
    from ignite.metrics import EpochMetric
ImportError: cannot import name 'EpochMetric'

Turns out ignite 0.1.0 doesnot contain 'EpochMetric' but the spec-file.txt installs ignite 0.1.0

**Comment by alfassy** [comment]
You are correct, if I recall correctly, we have used 0.1.0 with manual changes from their github.
version 0.1.1 already has the EpochMetric fuction,  you can try it out. If it doesn't work, I can upload our local version and make it apart of the onehsot package.

**Comment by alfassy** [comment]
Hi,

I have pushed a solution, the easiest way for you to have a working code is to start a fresh Conda environment, git clone the code directory and just follow the NEW setup instructions in the README.rst file.

The advanced short way would be, using your existing directory, pulling the changes from git, and then: "pip uninstall ignite" "pip uninstall oneshot" "pip uninstall experiment", then in the main project folder: "python setup.py build develop"

Regards,
Amit

**Comment by pratikm141** [comment]
ok I will try it out. Thanks

**Comment by alfassy** [comment]
@pratikm141 Hi, did it work for you? can I close this issue?

**Comment by pratikm141** [comment]
Yes its working now. Thanks
