### ISSUE TITLE
README files are missing

### ISSUE THREAD

**Issue by botcs** [leokarlin/LaSO#7]
Hi,

during the `python setup.py build develop`  call a few files were missing:
```
README_oneshot.rst
README_experiment.rst
README_ignite.rst
```

I found a workaround by just linking these filenames to the README.rst, but maybe it is not what you intended.

**Comment by alfassy** [comment]
Thank you!
I forgot to upload those 3 files to the git, what you did is ok as it doesn't really matter.
I have now uploaded these files to the git.
Amit
