### ISSUE TITLE
Resume epoch 49 is not found

### ISSUE THREAD

**Issue by botcs** [leokarlin/LaSO#9]
Hi,

Following the steps in `README.md` to reproduce the results, I tried to run:

`
python train_setops_stripped.py --inception_transform_input=False --resume_path=<path_to_LaSO_models>/resnet_base_model_only --resume_epoch=49 --init_inception=False --sets_basic_block_name=SetopResBasicBlock --sets_block_name=SetopResBlock_v1 --sets_network_name=SetOpsResModule --ops_latent_dim=8092 --ops_layer_num=2 --base_network_name=resnet50 --crop_size=224 --epochs=50 --train_base=False --coco_path=<path to local coco folder> --results_path=<base path for results>
`

I downloaded the `resnet_LaSO_models` from [here](https://drive.google.com/drive/folders/1FWg9gWM37SXk-bYOBH3-3Oe7uayzfiOd), but it contains no `networks_base_model_49<the remaining part>.pth` as the `--resume_epoch` would indicate, only 3, 4 and 6 is provided in [this sub-directory](https://drive.google.com/drive/folders/1NAB4TYquRUUfy7xTqgOlq_7b7B1p8uU1)

**Comment by alfassy** [comment]
49 is just a general number, you can use any saved epoch, let's say 4. I'll change it to 4 during the next commit.

**Comment by alfassy** [comment]
Fixed in the README, thank you
